name: Deploy API to DockerHub and AWS

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
    - name: Build Docker Image
      run: |
        docker build -t cv-inference-api .
    - name: Push to DockerHub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker tag cv-inference-api ${{ secrets.DOCKER_USERNAME }}/cv-inference-api:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/cv-inference-api:latest
